#ifndef KEYCODE_H
#define KEYCODE_H

#define K_UP 72
#define K_DOWN 80
#define K_LEFT 75
#define K_RIGHT 77
#define K_ENTER 13
#define K_ESC 27
#define K_TAB 9
#define K_F 59
#define K_F11 -123
#define K_F12 -122
#define ALTF 104
#define ALTN 112
#define ALTK1 16
#define ALTK2 30
#define ALTK3 44
#define K_PGUP 73
#define K_PGDN 81
#define K_HOME 71
#define K_END 79
#define K_INS 82
#define K_DEL 83
#define K_BACK 8
#define K_SPACE 32
#define CTRLF 94
#define CTRLK 1
#define SHIFT 84
#define KNUM0 82
#define K_NUM1 79
#define K_NUM2 80
#define K_NUM3 81
#define K_NUM4 75
#define K_NUM5 76
#define K_NUM6 77
#define K_NUM7 71
#define K_NUM8 72
#define K_NUM9 73
#define CTRLUP
#define CTRLDOWN
#define CTRLRIGHT
#define CTRLLEFT
#define ALTUP
#define ALTDOWN
#define ALTRIGHT
#define ALTLEFT

#endif